"""Lidar attribute tests: the fit must recover a model it is shown.

Run on CPU with numpy; the training loop itself needs CUDA and the kernel.
"""

from __future__ import annotations

import os

import numpy as np
import pytest

os.environ.setdefault("LIDRA_SKIP_INIT", "true")

from sam3d_objects.integrations.t4.lidar import (
    ObjectReturns,
    _face_normals,
    beam_grid,
    fit_reflectance,
)


def synthetic_returns(cos_power=1.0, range_power=0.0, weights=(60.0, 90.0, 120.0, 10.0), n=4000):
    """Measurements generated by a known model, to be recovered."""
    rng = np.random.default_rng(0)
    colour = rng.random((n, 3))
    cos_incidence = rng.uniform(0.2, 1.0, n)
    distance = rng.uniform(5.0, 60.0, n)
    reflectance = np.clip(colour @ np.asarray(weights[:3]) + weights[3], 0, 255)
    intensity = reflectance * cos_incidence**cos_power / distance**range_power
    return ObjectReturns(
        xyz=rng.random((n, 3)),
        intensity=intensity,
        distance=distance,
        cos_incidence=cos_incidence,
        colour=colour,
        view_index=np.zeros(n, np.int64),
    )


def test_fit_recovers_the_incidence_only_model():
    """A sensor that already range-compensates must not get a 1/R^2 fitted to it."""
    model = fit_reflectance(synthetic_returns(cos_power=1.0, range_power=0.0))
    assert model.cos_power == 1.0
    assert model.range_power == 0.0
    assert model.r2 > 0.99
    assert np.allclose(model.weights, [60.0, 90.0, 120.0, 10.0], atol=1.0)


def test_fit_recovers_the_range_dependent_model():
    model = fit_reflectance(synthetic_returns(cos_power=1.0, range_power=2.0))
    assert model.range_power == 2.0
    assert model.r2 > 0.99


def test_fit_prefers_no_geometry_when_the_data_shows_none():
    """Intensity that ignores geometry must not have geometry read into it."""
    model = fit_reflectance(synthetic_returns(cos_power=0.0, range_power=0.0))
    assert model.cos_power == 0.0
    assert model.range_power == 0.0


def test_predict_is_clipped_to_the_sensor_range():
    model = fit_reflectance(synthetic_returns())
    predicted = model.predict(np.array([[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]))
    assert predicted.min() >= 0.0 and predicted.max() <= 255.0


def test_face_normals_pick_the_face_the_hit_sits_on():
    size_wlh = (2.0, 4.0, 1.5)  # width, length, height
    local = np.array(
        [
            [2.0, 0.0, 0.0],  # past the +X (front) face
            [-2.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],  # past the +Y (left) face
            [0.0, 0.0, 0.75],  # roof
        ]
    )
    normals = _face_normals(local, size_wlh)
    assert np.allclose(normals[0], [1, 0, 0])
    assert np.allclose(normals[1], [-1, 0, 0])
    assert np.allclose(normals[2], [0, 1, 0])
    assert np.allclose(normals[3], [0, 0, 1])


def _grid_returns(n):
    return ObjectReturns(
        xyz=np.zeros((n, 3)),
        intensity=np.zeros(n),
        distance=np.zeros(n),
        cos_incidence=np.ones(n),
        colour=np.zeros((n, 3)),
        view_index=np.zeros(n, np.int64),
    )


def test_beam_grid_keeps_the_nearest_return_in_a_cell():
    """Two hits in one cell is a first-return sensor seeing the near one."""
    # Two points on the same bearing, 10 m apart in range.
    hits = np.array([[20.0, 0.0, 0.0], [30.0, 0.0, 0.0]])
    reflectance = np.array([0.2, 0.9])
    grid = beam_grid(_grid_returns(2), hits, np.eye(4), reflectance)

    assert grid is not None
    assert grid.n_measured == 1
    assert grid.ranges[0] == pytest.approx(20.0)
    assert grid.intensity[0] == pytest.approx(0.2)


def test_beam_grid_spans_the_whole_ring_and_tiles_divide_it():
    """The kernel's wrap arithmetic assumes a full-ring tile grid; hold to it."""
    rng = np.random.default_rng(1)
    hits = np.stack(
        [rng.uniform(8, 12, 500), rng.uniform(-2, 2, 500), rng.uniform(-1, 1, 500)], axis=1
    )
    grid = beam_grid(_grid_returns(500), hits, np.eye(4), rng.random(500))

    assert grid is not None
    assert grid.width % 8 == 0
    assert grid.width * grid.azimuth_resolution == pytest.approx(360.0)
    assert -85.0 <= grid.min_elevation < grid.max_elevation <= 85.0
    assert grid.n_measured > 0
    assert grid.rows.max() < grid.height and grid.cols.max() < grid.width


def test_beam_grid_handles_a_view_across_the_azimuth_seam():
    """A full ring has no seam to fall off; hits either side must both survive."""
    hits = np.array([[-10.0, 0.5, 0.0], [-10.0, -0.5, 0.0]])
    grid = beam_grid(_grid_returns(2), hits, np.eye(4), np.zeros(2))
    assert grid is not None
    assert grid.n_measured == 2
    # One sits just below +180 deg, the other just above -180 deg.
    assert grid.cols.max() - grid.cols.min() > grid.width // 2


def test_write_lidar_ply_adds_channels_and_keeps_the_originals(tmp_path):
    plyfile = pytest.importorskip("plyfile")
    from sam3d_objects.integrations.t4.asset import write_lidar_channels as write_lidar_ply

    n = 8
    dtype = [("x", "f4"), ("y", "f4"), ("z", "f4"), ("opacity", "f4"), ("f_dc_0", "f4")]
    data = np.zeros(n, dtype=dtype)
    for index, name in enumerate(data.dtype.names):
        data[name] = np.arange(n) + index
    source = tmp_path / "in.ply"
    plyfile.PlyData([plyfile.PlyElement.describe(data, "vertex")]).write(str(source))

    destination = tmp_path / "out.ply"
    intensity = np.linspace(0, 1, n).astype(np.float32)
    write_lidar_ply(source, destination, intensity, -intensity, 1 - intensity)

    written = plyfile.PlyData.read(str(destination)).elements[0]
    assert np.allclose(written["intensity"], intensity)
    assert np.allclose(written["raydrop_logit"], -intensity)
    assert np.allclose(written["lidar_opacity"], 1 - intensity)
    for index, name in enumerate(data.dtype.names):
        assert np.allclose(written[name], np.arange(n) + index), f"{name} was disturbed"


def test_write_lidar_ply_rejects_a_length_mismatch(tmp_path):
    plyfile = pytest.importorskip("plyfile")
    from sam3d_objects.integrations.t4.asset import write_lidar_channels as write_lidar_ply

    data = np.zeros(4, dtype=[("x", "f4")])
    source = tmp_path / "in.ply"
    plyfile.PlyData([plyfile.PlyElement.describe(data, "vertex")]).write(str(source))
    with pytest.raises(ValueError, match="4 splats"):
        write_lidar_ply(source, tmp_path / "out.ply", np.zeros(3), np.zeros(3), np.zeros(3))


def test_returns_cache_round_trips(tmp_path):
    """Refitting must see exactly what the extraction saw."""
    from sam3d_objects.integrations.t4.lidar import ViewReturns, load_returns, save_returns

    rng = np.random.default_rng(3)
    per_view = []
    for index, count in enumerate((7, 3, 11)):
        per_view.append(
            ViewReturns(
                returns=ObjectReturns(
                    xyz=rng.random((count, 3)),
                    intensity=rng.random(count) * 255,
                    distance=rng.random(count) * 50,
                    cos_incidence=rng.random(count),
                    colour=rng.random((count, 3)),
                    view_index=np.full(count, index, np.int64),
                ),
                hits_sensor=rng.random((count, 3)),
                viewmat=rng.random((4, 4)),
            )
        )
    path = tmp_path / "returns.npz"
    save_returns(path, per_view)
    restored = load_returns(path)

    assert len(restored) == len(per_view)
    for original, copy in zip(per_view, restored):
        for name in ("xyz", "intensity", "distance", "cos_incidence", "colour"):
            assert np.allclose(getattr(original.returns, name), getattr(copy.returns, name))
        assert np.allclose(original.hits_sensor, copy.hits_sensor)
        assert np.allclose(original.viewmat, copy.viewmat)
        assert (copy.returns.view_index == original.returns.view_index).all()


def test_returns_cache_refuses_a_stale_version(tmp_path):
    from sam3d_objects.integrations.t4.lidar import load_returns

    path = tmp_path / "returns.npz"
    np.savez(path, version=np.asarray(999), offsets=np.array([0]))
    with pytest.raises(ValueError, match="version 999"):
        load_returns(path)


def test_returns_cache_reads_each_array_once(tmp_path):
    """Views must slice into one decompression, not one copy of the file each.

    `np.load` on a zip decompresses on every key access, and a slice pins the
    whole array it came from -- indexing inside the per-view loop turns a 200 MB
    cache into hundreds of them and the process is killed.
    """
    from sam3d_objects.integrations.t4.lidar import ViewReturns, load_returns, save_returns

    rng = np.random.default_rng(4)
    per_view = [
        ViewReturns(
            returns=ObjectReturns(
                xyz=rng.random((5, 3)),
                intensity=rng.random(5),
                distance=rng.random(5),
                cos_incidence=rng.random(5),
                colour=rng.random((5, 3)),
                view_index=np.full(5, index, np.int64),
            ),
            hits_sensor=rng.random((5, 3)),
            viewmat=np.eye(4),
        )
        for index in range(3)
    ]
    path = tmp_path / "returns.npz"
    save_returns(path, per_view)
    restored = load_returns(path)

    # Disjoint slices of one array do not overlap, so compare what they view.
    assert restored[0].returns.xyz.base is restored[2].returns.xyz.base
    assert restored[0].hits_sensor.base is restored[2].hits_sensor.base


def _box_surface(rng, n=6000, size=(10.0, 2.6, 3.0)):
    """Points on the surface of a box, standing in for a vehicle's skin."""
    half = np.asarray(size) / 2
    points = rng.uniform(-1, 1, (n, 3)) * half
    face = rng.integers(0, 3, n)
    points[np.arange(n), face] = np.sign(points[np.arange(n), face]) * half[face]
    return points


def test_refine_recovers_a_known_scale_and_yaw():
    """The reconstruction is deliberately mis-scaled and turned; get it back."""
    from sam3d_objects.integrations.t4.lidar import refine_to_lidar

    rng = np.random.default_rng(5)
    measured = _box_surface(rng)

    yaw = np.radians(-3.0)
    scale = np.array([1.0, 1.16, 1.2])
    rotation = np.array(
        [[np.cos(yaw), -np.sin(yaw), 0], [np.sin(yaw), np.cos(yaw), 0], [0, 0, 1]]
    )
    # The splats are the measurements pushed through the error we want undone.
    splats = _box_surface(rng, n=20000) * scale @ rotation.T

    returns = ObjectReturns(
        xyz=measured,
        intensity=np.zeros(len(measured)),
        distance=np.full(len(measured), 20.0),
        cos_incidence=np.ones(len(measured)),
        colour=np.zeros((len(measured), 3)),
        view_index=np.zeros(len(measured), np.int64),
    )
    fit = refine_to_lidar(splats, returns, max_points=4000)

    assert fit.rms_after < fit.rms_before
    assert fit.yaw_deg == pytest.approx(3.0, abs=1.0)
    assert np.allclose(fit.scale, 1.0 / scale, rtol=0.08)


def test_transform_ply_moves_the_splats_and_keeps_the_rest(tmp_path):
    plyfile = pytest.importorskip("plyfile")
    pytest.importorskip("torch")
    from sam3d_objects.integrations.t4.asset import transform_ply

    n = 32
    names = ["x", "y", "z", "opacity", "f_dc_0"]
    names += [f"scale_{i}" for i in range(3)] + [f"rot_{i}" for i in range(4)]
    data = np.zeros(n, dtype=[(name, "f4") for name in names])
    rng = np.random.default_rng(6)
    for axis in "xyz":
        data[axis] = rng.uniform(-2, 2, n)
    data["opacity"] = rng.uniform(-1, 1, n)
    data["f_dc_0"] = rng.uniform(-1, 1, n)
    for index in range(3):
        data[f"scale_{index}"] = np.log(rng.uniform(0.01, 0.05, n))
    data["rot_0"] = 1.0

    source = tmp_path / "in.ply"
    plyfile.PlyData([plyfile.PlyElement.describe(data, "vertex")]).write(str(source))
    destination = tmp_path / "out.ply"
    transform_ply(source, destination, np.diag([2.0, 2.0, 2.0]), np.array([1.0, 0.0, 0.0]))

    written = plyfile.PlyData.read(str(destination)).elements[0]
    assert np.allclose(written["x"], data["x"] * 2 + 1, atol=1e-4)
    assert np.allclose(written["y"], data["y"] * 2, atol=1e-4)
    # A uniform scaling doubles every radius; log-scale gains log 2.
    assert np.allclose(written["scale_0"], data["scale_0"] + np.log(2), atol=1e-4)
    # Colour and opacity are not geometry and must come through untouched.
    assert np.allclose(written["opacity"], data["opacity"])
    assert np.allclose(written["f_dc_0"], data["f_dc_0"])


def test_refine_does_not_run_away_when_only_one_face_is_measured():
    """A one-sided fit inflates the cloud until every return finds a neighbour.

    The lidar only ever sees the near side, so the objective has to penalise
    splats that drift away from the measurements as well, or the scale grows
    without bound -- which is what turned a 3 m truck into a 10 m one.
    """
    from sam3d_objects.integrations.t4.lidar import refine_to_lidar

    rng = np.random.default_rng(7)
    splats = _box_surface(rng, n=20000)
    # Returns on the +Y face alone, exactly where the splats already are. With
    # one face and a free translation the scale along Y is not identifiable, so
    # what is asserted below is only that the fit does not INFLATE -- the
    # failure that turned a 3 m truck into a 10 m one.
    measured = _box_surface(rng, n=6000)
    measured = measured[measured[:, 1] > 1.2]

    returns = ObjectReturns(
        xyz=measured,
        intensity=np.zeros(len(measured)),
        distance=np.full(len(measured), 20.0),
        cos_incidence=np.ones(len(measured)),
        colour=np.zeros((len(measured), 3)),
        view_index=np.zeros(len(measured), np.int64),
    )
    fit = refine_to_lidar(splats, returns, max_points=4000)

    assert (fit.scale <= 1.2).all(), fit.scale
    assert abs(fit.yaw_deg) < 3.0


def test_refine_recovers_a_scale_both_faces_constrain():
    """Opposite faces pin the axis, so the fit has to land on the true scale."""
    from sam3d_objects.integrations.t4.lidar import refine_to_lidar

    rng = np.random.default_rng(8)
    measured = _box_surface(rng, n=8000)
    measured = measured[np.abs(measured[:, 1]) > 1.2]  # both +Y and -Y faces
    splats = _box_surface(rng, n=20000) * np.array([1.0, 1.25, 1.0])

    returns = ObjectReturns(
        xyz=measured,
        intensity=np.zeros(len(measured)),
        distance=np.full(len(measured), 20.0),
        cos_incidence=np.ones(len(measured)),
        colour=np.zeros((len(measured), 3)),
        view_index=np.zeros(len(measured), np.int64),
    )
    fit = refine_to_lidar(splats, returns, max_points=4000)
    assert fit.scale[1] == pytest.approx(1 / 1.25, rel=0.12), fit.scale
